### ISSUE TITLE
Reset Button and connector

### ISSUE THREAD

**Issue by ottojo** [ToolboxPlane/FlightControllerBoard#1]

**Comment by ottojo** [comment]
1. Specify Connector
2. Reset button is available on the Nucleo board
@aul12

**Comment by aul12** [comment]
1. A simple two Pin connector which pulls Reset to GND.
2. The button is on the breakout board, if we mount the pcb inside of the plane it isn't possible to use the button

**Comment by ottojo** [comment]
added connector
